# Generated by Django 3.2.16 on 2022-12-13 21:35

from django.db import migrations, models
import django.db.models.deletion
import enterprise.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('family_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('father_name', models.CharField(max_length=255, verbose_name='Отчество')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название организации')),
                ('description', models.TextField(verbose_name='Описание организации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprises', to='enterprise.enterprise', verbose_name='ID родительского предприятия')),
            ],
            options={
                'verbose_name': 'Предприятие',
                'verbose_name_plural': 'Предприятия',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CardEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MANAGER', 'Менеджер'), ('DEVELOPER', 'Разработчик'), ('DIRECTOR', 'Руководитель'), ('ACCOUNTANT', 'Бухгалтер')], default=enterprise.enums.RolesEmployeeEnum['DIRECTOR'], max_length=50, verbose_name='Должность')),
                ('salary', models.PositiveIntegerField(verbose_name='Заработная плата')),
                ('date_start', models.DateField(verbose_name='Дата трудоустройства')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='enterprise.employee', verbose_name='Сотрудник')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='enterprise.enterprise', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Карточка сотрудника',
                'verbose_name_plural': 'Карточки сотрудников',
                'ordering': ('-created_at',),
            },
        ),
    ]
