# Generated by Django 3.2.16 on 2022-12-14 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_alter_enterprise_parent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enterprise',
            unique_together={('parent', 'name')},
        ),
    ]
